### PR TITLE
fix to histogram legend

### PR DESCRIPTION
**Pull request by vpbrendel**
I think you got this right in the comments but not in the code ...

Please take a look.
Thanks, Volker

### CODE REVIEW

**Comment by MalteThodberg** [comment]
Dear Volker,

I just double checked, it appears the plus/strand colors are showing correctly in the CAGEfightR vignette, but not in the CAGEfightR workflow!

I will double check what is causing this, but will be after New Years.

**Comment by MalteThodberg** [comment]
@vpbrendel : Had a look again at this now - can you point me towards where you think the histogram  legends are wrong?

**Comment by vpbrendel** [comment]
It's in the track.R file. I just went through your examples/tutorials, if I recall correctly, and looked at the histogram.

**Comment by MalteThodberg** [comment]
There was indeed a behind the curtains change to Gviz which caused the colors to flip.

Can you see if there's still an issue in the most recent devel build?: https://bioconductor.org/packages/devel/bioc/vignettes/CAGEfightR/inst/doc/Introduction_to_CAGEfightR.html

I think this look ok:
image

**Comment by vpbrendel** [comment]
Yes this looks ok. Thanks.

**Comment by MalteThodberg** [comment]
Did you otherwise have trouble when using CAGEfightR? E.g. when you use the plotting functions, is it looking alright?

**Comment by vpbrendel** [comment]
I have not worked on our TSS project for a while, but at the time, this was the one error I found. I could send you feature requests when I get back to this; e.g. a description of how to generate a "design" data frame - I remember that took me a while to figure out on my own.

**Comment by MalteThodberg** [comment]
It might have been caused by CAGEfightR not explicitly requiring the newest version of Gviz. I will update so CAGEfightR checks for this now.

If all is good, I will close this request. 

Of course happy to help with other questions/request!

**Pull request closed without merging**
